import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// Color palette (LM Compass warm brown-orange)
const PRIMARY_RGB: [number, number, number] = [176, 90, 45];
const PRIMARY_LIGHT_RGB: [number, number, number] = [245, 230, 220];
const WHITE: [number, number, number] = [255, 255, 255];
const TEXT_DARK: [number, number, number] = [30, 30, 30];
const TEXT_MUTED: [number, number, number] = [120, 110, 105];
const BORDER_COLOR: [number, number, number] = [220, 215, 210];

const CHART_HEX = [
  "#6366f1", "#f59e0b", "#10b981", "#ef4444", "#8b5cf6",
  "#ec4899", "#14b8a6", "#f97316", "#06b6d4", "#84cc16",
];

// Types
export interface ReportExperimentMeta {
  title: string;
  authorName: string;
  createdAt: string;
  queryCount: number;
  models: string[];
  rubricName: string;
  evalMethod: string;
}

export interface ReportPerformanceMetric {
  label: string;
  values: string[];
  winnerIndexes: number[];
}

export interface ReportPerformanceSummary {
  models: string[];
  metrics: ReportPerformanceMetric[];
}

export interface ReportKendallRow {
  judgeA: string;
  judgeB: string;
  tauB: number;
  agreement: string;
  comparedPairs: number;
  queryCount: number;
}

export interface ReportItemRow {
  index: number;
  query: string;
  winnerModel: string;
  score: string;
}

export interface ReportChartData {
  avgScores: { model: string; avgScore: number }[];
  wins: { name: string; value: number }[];
}

export interface ExperimentReportInput {
  meta: ReportExperimentMeta;
  performanceSummary: ReportPerformanceSummary | null;
  kendallRows: ReportKendallRow[];
  itemRows: ReportItemRow[];
  chartData: ReportChartData;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function formatModelLabel(model: string): string {
  const shortName = model.split("/").pop() || model;
  return shortName.length > 28 ? `${shortName.slice(0, 28)}…` : shortName;
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleString("en-US", {
      dateStyle: "long",
      timeStyle: "short",
    });
  } catch {
    return iso;
  }
}

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [
    parseInt(h.substring(0, 2), 16),
    parseInt(h.substring(2, 4), 16),
    parseInt(h.substring(4, 6), 16),
  ];
}

function addPageFooters(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    doc.setDrawColor(...BORDER_COLOR);
    doc.setLineWidth(0.3);
    doc.line(20, pageH - 14, pageW - 20, pageH - 14);

    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED);
    doc.text("Generated by LM Compass", 20, pageH - 9);
    doc.text(`Page ${i} of ${pageCount}`, pageW - 20, pageH - 9, {
      align: "right",
    });
  }
}

// Chart rendering to canvas → data URL

function chartLabel(model: string, maxLen = 20): string {
  const shortName = model.split("/").pop() || model;
  return shortName.length > maxLen ? `${shortName.slice(0, maxLen)}…` : shortName;
}

function renderBarChartToDataURL(
  data: { model: string; avgScore: number }[],
  width: number,
  height: number
): string {
  const canvas = document.createElement("canvas");
  canvas.width = width * 2; // 2x for retina
  canvas.height = height * 2;
  const ctx = canvas.getContext("2d")!;
  ctx.scale(2, 2);
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, width, height);

  if (data.length === 0) return canvas.toDataURL("image/png");

  const margin = { top: 35, right: 30, bottom: 80, left: 65 };
  const chartW = width - margin.left - margin.right;
  const chartH = height - margin.top - margin.bottom;

  const values = data.map((d) => d.avgScore);
  const minVal = Math.min(...values);
  const maxVal = Math.max(...values);
  const spread = maxVal - minVal || 1;
  const padding = Math.max(0.4, spread * 0.35);
  const domainMin = Math.max(0, Math.floor((minVal - padding) * 10) / 10);
  const domainMax = Math.min(100, Math.ceil((maxVal + padding) * 10) / 10);
  const domainRange = domainMax - domainMin || 1;

  const barWidth = Math.min(36, chartW / data.length - 12);

  ctx.strokeStyle = "#e5e5e5";
  ctx.lineWidth = 0.5;
  const gridSteps = 5;
  for (let i = 0; i <= gridSteps; i++) {
    const y = margin.top + chartH - (i / gridSteps) * chartH;
    ctx.beginPath();
    ctx.moveTo(margin.left, y);
    ctx.lineTo(margin.left + chartW, y);
    ctx.stroke();

    const val = domainMin + (i / gridSteps) * domainRange;
    ctx.fillStyle = "#888";
    ctx.font = "11px sans-serif";
    ctx.textAlign = "right";
    ctx.fillText(val.toFixed(1), margin.left - 8, y + 4);
  }

  data.forEach((d, i) => {
    const x =
      margin.left + (i + 0.5) * (chartW / data.length) - barWidth / 2;
    const normalizedH = ((d.avgScore - domainMin) / domainRange) * chartH;
    const y = margin.top + chartH - normalizedH;
    const color = CHART_HEX[i % CHART_HEX.length];

    ctx.fillStyle = color;
    const radius = 4;
    ctx.beginPath();
    ctx.moveTo(x + radius, y);
    ctx.lineTo(x + barWidth - radius, y);
    ctx.quadraticCurveTo(x + barWidth, y, x + barWidth, y + radius);
    ctx.lineTo(x + barWidth, margin.top + chartH);
    ctx.lineTo(x, margin.top + chartH);
    ctx.lineTo(x, y + radius);
    ctx.quadraticCurveTo(x, y, x + radius, y);
    ctx.fill();

    ctx.fillStyle = "#333";
    ctx.font = "bold 11px sans-serif";
    ctx.textAlign = "center";
    ctx.fillText(d.avgScore.toFixed(2), x + barWidth / 2, y - 8);
    ctx.fillStyle = "#666";
    ctx.font = "10px sans-serif";
    ctx.save();
    ctx.translate(x + barWidth / 2, margin.top + chartH + 10);
    ctx.rotate(-0.45);
    ctx.textAlign = "right";
    ctx.fillText(chartLabel(d.model), 0, 0);
    ctx.restore();
  });

  return canvas.toDataURL("image/png");
}

function renderPieChartToDataURL(
  data: { name: string; value: number }[],
  width: number,
  height: number
): string {
  const canvas = document.createElement("canvas");
  canvas.width = width * 2;
  canvas.height = height * 2;
  const ctx = canvas.getContext("2d")!;
  ctx.scale(2, 2);
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, width, height);

  if (data.length === 0) return canvas.toDataURL("image/png");

  const total = data.reduce((s, d) => s + d.value, 0);
  if (total === 0) return canvas.toDataURL("image/png");

  const legendAreaHeight = 40;
  const drawableH = height - legendAreaHeight;

  const cx = width / 2;
  const cy = drawableH / 2;
  const radius = Math.min(cx, cy) * 0.40;
  const labelRadius = radius + 22;
  let startAngle = -Math.PI / 2;

  data.forEach((d, i) => {
    const sliceAngle = (d.value / total) * 2 * Math.PI;
    const endAngle = startAngle + sliceAngle;
    const color = CHART_HEX[i % CHART_HEX.length];

    ctx.fillStyle = color;
    ctx.beginPath();
    ctx.moveTo(cx, cy);
    ctx.arc(cx, cy, radius, startAngle, endAngle);
    ctx.closePath();
    ctx.fill();

    const midAngle = startAngle + sliceAngle / 2;
    let lx = cx + Math.cos(midAngle) * labelRadius;
    let ly = cy + Math.sin(midAngle) * labelRadius;
    const labelText = `${chartLabel(d.name, 18)} (${d.value})`;

    ctx.font = "10px sans-serif";
    const isRight = Math.cos(midAngle) > 0;
    ctx.textAlign = isRight ? "left" : "right";

    const textW = ctx.measureText(labelText).width;
    if (isRight) {
      lx = Math.max(8, Math.min(lx, width - textW - 8));
    } else {
      lx = Math.min(width - 8, Math.max(textW + 8, lx));
    }
    ly = Math.max(14, Math.min(ly, drawableH - 8));

    ctx.fillStyle = "#333";
    ctx.fillText(labelText, lx, ly);

    startAngle = endAngle;
  });

  const legendStartY = drawableH + 8;
  const legendPadX = 16;
  const rowHeight = 16;
  let legendX = legendPadX;
  let legendRow = 0;
  ctx.font = "10px sans-serif";

  data.forEach((d, i) => {
    const color = CHART_HEX[i % CHART_HEX.length];
    const label = chartLabel(d.name, 22);
    const itemWidth = 14 + ctx.measureText(label).width + 18;

    if (legendX + itemWidth > width - legendPadX && legendX > legendPadX) {
      legendRow += 1;
      legendX = legendPadX;
    }

    const yPos = legendStartY + legendRow * rowHeight;

    ctx.fillStyle = color;
    ctx.beginPath();
    ctx.arc(legendX + 5, yPos, 4, 0, Math.PI * 2);
    ctx.fill();

    ctx.fillStyle = "#555";
    ctx.textAlign = "left";
    ctx.fillText(label, legendX + 14, yPos + 4);

    legendX += itemWidth;
  });

  return canvas.toDataURL("image/png");
}

// Main export function
export function generateExperimentReport(input: ExperimentReportInput) {
  const { meta, performanceSummary, kendallRows, itemRows, chartData } = input;

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth(); // 210
  let y = 0;

  // 1. Header bar
  doc.setFillColor(...PRIMARY_RGB);
  doc.rect(0, 0, pageW, 38, "F");

  doc.setTextColor(...WHITE);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("LM Compass", 20, 16);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Experiment Report", 20, 24);

  doc.setFontSize(8);
  doc.text(
    `Generated ${new Date().toLocaleString("en-US", { dateStyle: "long", timeStyle: "short" })}`,
    20,
    32
  );

  y = 48;

  // 2. Experiment info block
  doc.setFillColor(...PRIMARY_LIGHT_RGB);
  doc.roundedRect(20, y, pageW - 40, 36, 3, 3, "F");

  doc.setTextColor(...TEXT_DARK);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(meta.title || "Untitled Experiment", 28, y + 10);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...TEXT_MUTED);

  const infoLine1 = `By ${meta.authorName}  •  ${formatDate(meta.createdAt)}`;
  doc.text(infoLine1, 28, y + 18);

  const infoLine2 = `${meta.queryCount} queries  •  ${meta.models.length} model${meta.models.length !== 1 ? "s" : ""}  •  Rubric: ${meta.rubricName}  •  Method: ${meta.evalMethod.replace(/-/g, " ")}`;
  doc.text(infoLine2, 28, y + 25);

  const modelsList = `Models: ${meta.models.map(formatModelLabel).join(", ")}`;
  doc.setFontSize(8);
  doc.text(modelsList, 28, y + 31, { maxWidth: pageW - 56 });

  y += 44;

  // 3. Highlight summary
  if (performanceSummary && performanceSummary.metrics.length > 0) {
    const winRateMetric = performanceSummary.metrics.find(
      (m) => m.label === "Win Rate"
    );
    if (winRateMetric && winRateMetric.winnerIndexes.length > 0) {
      const winnerIdx = winRateMetric.winnerIndexes[0];
      const winnerModel = performanceSummary.models[winnerIdx];
      const winRate = winRateMetric.values[winnerIdx];

      const avgScoreMetric = performanceSummary.metrics.find(
        (m) => m.label === "Average Score"
      );
      const avgScore = avgScoreMetric
        ? avgScoreMetric.values[winnerIdx]
        : null;

      doc.setFillColor(...PRIMARY_RGB);
      doc.roundedRect(20, y, pageW - 40, 20, 3, 3, "F");

      doc.setTextColor(...WHITE);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");

      let highlight = `${formatModelLabel(winnerModel)} answered your queries correctly most often with a ${winRate} win rate`;
      if (avgScore) {
        highlight += ` and an average score of ${avgScore}`;
      }
      highlight += ".";

      doc.text(highlight, 28, y + 12, { maxWidth: pageW - 56 });
      y += 28;
    }
  }

  // 4. Charts
  if (chartData.avgScores.length > 0) {
    doc.setTextColor(...TEXT_DARK);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text("Charts", 20, y + 2);
    y += 8;

    const chartW = (pageW - 50) / 2;
    const chartH = 80;

    const barImg = renderBarChartToDataURL(
      chartData.avgScores,
      chartW * 3,
      chartH * 3
    );
    const pieImg =
      chartData.wins.length > 0
        ? renderPieChartToDataURL(chartData.wins, chartW * 3, chartH * 3)
        : null;

    // Bar chart
    doc.setDrawColor(...BORDER_COLOR);
    doc.setLineWidth(0.3);
    doc.roundedRect(20, y, chartW, chartH, 2, 2);
    doc.addImage(barImg, "PNG", 20, y, chartW, chartH);

    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED);
    doc.text("Average Score by Model", 20 + chartW / 2, y + chartH + 5, {
      align: "center",
    });

    // Pie chart
    if (pieImg) {
      const pieX = 30 + chartW;
      doc.roundedRect(pieX, y, chartW, chartH, 2, 2);
      doc.addImage(pieImg, "PNG", pieX, y, chartW, chartH);
      doc.text("Queries Won by Model", pieX + chartW / 2, y + chartH + 5, {
        align: "center",
      });
    }

    y += chartH + 14;
  }

  // 5. Performance Summary table
  if (performanceSummary) {
    if (y > 230) {
      doc.addPage();
      y = 20;
    }

    doc.setTextColor(...TEXT_DARK);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text("Model Performance Summary", 20, y + 2);
    y += 6;

    const head = [
      ["Metric", ...performanceSummary.models.map(formatModelLabel)],
    ];
    const body = performanceSummary.metrics.map((metric) => [
      metric.label,
      ...metric.values,
    ]);

    autoTable(doc, {
      startY: y,
      head,
      body,
      margin: { left: 20, right: 20 },
      styles: {
        fontSize: 8,
        cellPadding: 3,
        lineColor: BORDER_COLOR,
        lineWidth: 0.2,
      },
      headStyles: {
        fillColor: PRIMARY_RGB,
        textColor: WHITE,
        fontStyle: "bold",
        fontSize: 8,
      },
      alternateRowStyles: {
        fillColor: [250, 247, 244],
      },
      didParseCell: (data) => {
        if (data.section === "body" && data.column.index > 0) {
          const metric = performanceSummary.metrics[data.row.index];
          if (metric && metric.winnerIndexes.includes(data.column.index - 1)) {
            data.cell.styles.fontStyle = "bold";
            data.cell.styles.textColor = PRIMARY_RGB;
          }
        }
      },
    });

    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // 6. Kendall's Tau-b table
  if (kendallRows.length > 0) {
    if (y > 240) {
      doc.addPage();
      y = 20;
    }

    doc.setTextColor(...TEXT_DARK);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text("Judge Agreement (Kendall's Tau-b)", 20, y + 2);
    y += 6;

    autoTable(doc, {
      startY: y,
      head: [["Judge A", "Judge B", "Tau-b", "Agreement", "Pairs", "Queries"]],
      body: kendallRows.map((row) => [
        formatModelLabel(row.judgeA),
        formatModelLabel(row.judgeB),
        Number.isFinite(row.tauB) ? row.tauB.toFixed(3) : "—",
        row.agreement,
        String(row.comparedPairs),
        String(row.queryCount),
      ]),
      margin: { left: 20, right: 20 },
      styles: {
        fontSize: 8,
        cellPadding: 3,
        lineColor: BORDER_COLOR,
        lineWidth: 0.2,
      },
      headStyles: {
        fillColor: PRIMARY_RGB,
        textColor: WHITE,
        fontStyle: "bold",
        fontSize: 8,
      },
      alternateRowStyles: {
        fillColor: [250, 247, 244],
      },
    });

    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // 7. Per-item results table
  if (itemRows.length > 0) {
    if (y > 240) {
      doc.addPage();
      y = 20;
    }

    doc.setTextColor(...TEXT_DARK);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text("Query Results", 20, y + 2);
    y += 6;

    autoTable(doc, {
      startY: y,
      head: [["#", "Query", "Winner Model", "Score"]],
      body: itemRows.map((row) => [
        String(row.index),
        row.query,
        formatModelLabel(row.winnerModel),
        row.score,
      ]),
      margin: { left: 20, right: 20 },
      columnStyles: {
        0: { cellWidth: 10 },
        1: { cellWidth: "auto" },
        2: { cellWidth: 40 },
        3: { cellWidth: 18 },
      },
      styles: {
        fontSize: 8,
        cellPadding: 3,
        lineColor: BORDER_COLOR,
        lineWidth: 0.2,
        overflow: "linebreak",
      },
      headStyles: {
        fillColor: PRIMARY_RGB,
        textColor: WHITE,
        fontStyle: "bold",
        fontSize: 8,
      },
      alternateRowStyles: {
        fillColor: [250, 247, 244],
      },
    });
  }

  // Footer on all pages
  addPageFooters(doc);

  // Save
  const safeName = (meta.title || "experiment")
    .replace(/[^a-zA-Z0-9 ]/g, "")
    .replace(/\s+/g, "_")
    .toLowerCase();
  doc.save(`${safeName}_report.pdf`);
}
